'use client';

import React, { useState, useEffect } from 'react';
import { Task, Priority, LabelColor } from '@/types';
import { Modal } from '../ui/Modal';
import { Input } from '../ui/Input';
import { Textarea } from '../ui/Textarea';
import { Select } from '../ui/Select';
import { Button } from '../ui/Button';
import { ToggleBadge } from '../ui/ToggleBadge';
import { MarkdownBox } from '../ui/MarkdownBox';
import { DUMMY_USERS } from '@/lib/dummy-data';
import { useKanbanBoard } from '@/hooks/useKanbanBoard';
import { Sparkles, Plus, X } from 'lucide-react';
import { cn } from '@/lib/utils';

interface TaskModalProps {
  isOpen: boolean;
  onClose: () => void;
  initialData?: Task;
  onSave: (task: Task) => void;
  onDelete?: (taskId: string) => void;
}

export function TaskModal({ isOpen, onClose, initialData, onSave, onDelete }: TaskModalProps) {
  const { board, addLabel, deleteLabel } = useKanbanBoard();
  
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [status, setStatus] = useState(board.columns[0]?.id || '');
  const [priority, setPriority] = useState<Priority>('Medium');
  const [dueDate, setDueDate] = useState('');
  const [assigneeId, setAssigneeId] = useState('');
  const [selectedLabels, setSelectedLabels] = useState<string[]>([]);
  const [progress, setProgress] = useState(0);
  
  const [previewMode, setPreviewMode] = useState(false);
  const [isAddingTag, setIsAddingTag] = useState(false);
  const [newTagName, setNewTagName] = useState('');
  const [newTagColor, setNewTagColor] = useState<LabelColor>('outline');
  
  // Issue #16: Replace window.confirm with inline confirmation
  const [confirmingDeleteLabelId, setConfirmingDeleteLabelId] = useState<string | null>(null);
  // Issue #16: Replace alert with inline validation
  const [titleError, setTitleError] = useState<string | null>(null);

  useEffect(() => {
    if (isOpen) {
      if (initialData) {
        setTitle(initialData.title);
        setDescription(initialData.description);
        setStatus(initialData.status);
        setPriority(initialData.priority);
        setDueDate(initialData.dueDate || '');
        setAssigneeId(initialData.assignee?.id || '');
        setSelectedLabels(initialData.labels?.map(l => l.id) || []);
        setProgress(initialData.progress || 0);
      } else {
        setTitle('');
        setDescription('');
        setStatus(board.columns[0]?.id || '');
        setPriority('Medium');
        setDueDate('');
        setAssigneeId('');
        setSelectedLabels([]);
        setProgress(0);
      }
      setPreviewMode(false);
      setIsAddingTag(false);
      setNewTagName('');
      setConfirmingDeleteLabelId(null);
      setTitleError(null);
    }
  }, [isOpen, initialData, board.columns]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim()) return;

    const assignee = DUMMY_USERS.find(u => u.id === assigneeId);
    const labels = (board.labels || []).filter(l => selectedLabels.includes(l.id));

    const taskData: Task = {
      // Issue #3: crypto.randomUUID() instead of Date.now()
      id: initialData?.id || crypto.randomUUID(),
      title,
      description,
      status,
      priority,
      labels,
      assignee,
      progress,
      dueDate: dueDate || undefined,
    };

    onSave(taskData);
    onClose();
  };

  const toggleLabel = (labelId: string) => {
    setSelectedLabels(prev => 
      prev.includes(labelId) ? prev.filter(id => id !== labelId) : [...prev, labelId]
    );
  };

  const handleGenerateAI = () => {
    if (!title) {
      // Issue #16: Inline error instead of alert()
      setTitleError('Please enter a title first so the AI knows what to generate!');
      return;
    }
    setTitleError(null);
    const dummyDescription = `This is an auto-generated description for **${title}**.\n\n### Key Requirements\n- Ensure proper testing\n- Follow design system guidelines\n- Update documentation if needed\n\n*Generated by AI assistant.*`;
    setDescription(dummyDescription);
    setPreviewMode(true);
  };

  const handleAddTag = () => {
    if (newTagName.trim()) {
      // Issue #3: crypto.randomUUID() instead of Date.now()
      const newLabelId = crypto.randomUUID();
      addLabel(newTagName.trim(), newTagColor, newLabelId);
      setSelectedLabels(prev => [...prev, newLabelId]);
      setNewTagName('');
      setIsAddingTag(false);
    }
  };

  const handleDeleteLabel = (labelId: string) => {
    if (confirmingDeleteLabelId === labelId) {
      // Second click — actually delete
      deleteLabel(labelId);
      setSelectedLabels(prev => prev.filter(id => id !== labelId));
      setConfirmingDeleteLabelId(null);
    } else {
      // First click — show confirmation
      setConfirmingDeleteLabelId(labelId);
      // Auto-reset after 3 seconds if not confirmed
      setTimeout(() => setConfirmingDeleteLabelId(prev => prev === labelId ? null : prev), 3000);
    }
  };

  const isEditing = !!initialData;
  const availableLabels = board.labels || [];

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title={isEditing ? 'Edit Task' : 'Create New Task'}
      layoutId={isEditing ? initialData.id : 'new-task'}
    >
      <form onSubmit={handleSubmit} className="flex flex-col gap-6">
        
        <div className="flex flex-col gap-2">
          <label className="text-sm font-medium text-gray-900 dark:text-gray-100">Title</label>
          <Input 
            value={title} 
            onChange={(e) => {
              setTitle(e.target.value);
              if (titleError) setTitleError(null);
            }} 
            placeholder="e.g. Build UI layout" 
            autoFocus
            required 
          />
          {titleError && (
            <p className="text-xs text-red-500">{titleError}</p>
          )}
        </div>

        <div className="flex flex-col gap-2">
          <div className="flex items-center justify-between">
            <label className="text-sm font-medium text-gray-900 dark:text-gray-100">Description</label>
            <div className="flex items-center gap-3">
              <button
                type="button"
                onClick={handleGenerateAI}
                className="flex items-center gap-1.5 px-2 py-1 text-xs font-medium rounded-md border border-gray-200 dark:border-white/20 bg-white dark:bg-black text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-white/5 transition-colors"
              >
                <Sparkles className="w-3.5 h-3.5 text-gray-900 dark:text-gray-100" />
                <span className="hidden sm:inline">Auto-generate</span>
              </button>
              <button 
                type="button" 
                onClick={() => setPreviewMode(!previewMode)}
                className="text-xs text-gray-900 dark:text-gray-100 font-medium hover:underline"
              >
                {previewMode ? 'Edit Markdown' : 'Preview'}
              </button>
            </div>
          </div>
          {previewMode ? (
            <MarkdownBox content={description || '*No description provided.*'} className="min-h-32" />
          ) : (
            <Textarea 
              value={description} 
              onChange={(e) => setDescription(e.target.value)} 
              placeholder="Use markdown (**bold**, _italic_, - lists)" 
              className="min-h-32"
            />
          )}
        </div>

        <div className="flex flex-col gap-2">
          <div className="flex items-center justify-between">
            <label className="text-sm font-medium text-gray-900 dark:text-gray-100">Progress</label>
            <span className="text-xs font-medium text-gray-500">{progress}%</span>
          </div>
          <input 
            type="range" 
            min="0" max="100" 
            value={progress}
            onChange={(e) => setProgress(Number(e.target.value))}
            className="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer dark:bg-gray-800"
          />
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-6">
          <div className="flex flex-col gap-4">
            <div className="flex flex-col gap-2">
              <label className="text-sm font-medium text-gray-900 dark:text-gray-100">Status</label>
              <Select value={status} onChange={(e) => setStatus(e.target.value)}>
                {board.columns.map(col => (
                  <option key={col.id} value={col.id}>{col.title}</option>
                ))}
              </Select>
            </div>

            <div className="flex flex-col gap-2">
              <label className="text-sm font-medium text-gray-900 dark:text-gray-100">Priority</label>
              <Select value={priority} onChange={(e) => setPriority(e.target.value as Priority)}>
                <option value="Low">Low</option>
                <option value="Medium">Medium</option>
                <option value="High">High</option>
              </Select>
            </div>
          </div>

          <div className="flex flex-col gap-4">
            <div className="flex flex-col gap-2">
              <label className="text-sm font-medium text-gray-900 dark:text-gray-100">Assignee</label>
              <Select value={assigneeId} onChange={(e) => setAssigneeId(e.target.value)}>
                <option value="">Unassigned</option>
                {DUMMY_USERS.map(user => (
                  <option key={user.id} value={user.id}>{user.name}</option>
                ))}
              </Select>
            </div>

            <div className="flex flex-col gap-2">
              <label className="text-sm font-medium text-gray-900 dark:text-gray-100">Due Date</label>
              <Input 
                type="date" 
                value={dueDate} 
                onChange={(e) => setDueDate(e.target.value)} 
              />
            </div>
          </div>
        </div>

        <div className="flex flex-col gap-2">
          <div className="flex items-center justify-between">
            <label className="text-sm font-medium text-gray-900 dark:text-gray-100">Labels</label>
          </div>
          <div className="flex flex-wrap items-center gap-2">
            {availableLabels.map(label => {
              const isSelected = selectedLabels.includes(label.id);
              const isConfirmingDelete = confirmingDeleteLabelId === label.id;
              return (
                <div key={label.id} className="group relative flex items-center">
                  {/* Issue #14: Proper LabelColor type — no more `as any` */}
                  <ToggleBadge
                    selected={isSelected}
                    selectedColor={label.color}
                    onClick={() => toggleLabel(label.id)}
                  >
                    {label.name}
                  </ToggleBadge>
                  
                  {/* Issue #16: Inline confirmation instead of window.confirm */}
                  <button 
                    type="button"
                    onClick={(e) => {
                      e.stopPropagation();
                      handleDeleteLabel(label.id);
                    }}
                    className={cn(
                      "absolute -top-1.5 -right-1.5 items-center justify-center w-4 h-4 text-white rounded-full shadow-sm z-10 transition-colors",
                      isConfirmingDelete ? "flex bg-red-700 animate-pulse" : "hidden group-hover:flex bg-red-500 hover:bg-red-600"
                    )}
                    title={isConfirmingDelete ? 'Click again to confirm deletion' : 'Delete label'}
                  >
                    <X className="w-2.5 h-2.5" />
                  </button>
                </div>
              );
            })}
            
            {!isAddingTag ? (
              <button
                type="button"
                onClick={() => setIsAddingTag(true)}
                className="flex items-center gap-1 px-2 py-1 text-xs font-medium rounded-full border border-dashed border-gray-300 dark:border-white/30 text-gray-500 hover:bg-gray-50 dark:hover:bg-white/5 transition-colors"
              >
                <Plus className="w-3 h-3" />
                Add Tag
              </button>
            ) : (
              <div className="flex items-center gap-2 p-1 border border-gray-200 dark:border-white/20 rounded-md bg-gray-50 dark:bg-white/5">
                <Input 
                  value={newTagName}
                  onChange={(e) => setNewTagName(e.target.value)}
                  placeholder="Tag name"
                  className="h-6 text-[10px] w-20 px-1 py-0 min-h-0"
                  autoFocus
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') {
                      e.preventDefault();
                      handleAddTag();
                    }
                  }}
                />
                <div className="flex gap-1 ml-1">
                  <button type="button" className="p-1 hover:bg-gray-200 dark:hover:bg-gray-700 rounded text-gray-700 dark:text-gray-300" onClick={handleAddTag}>
                    <Plus className="w-3 h-3" />
                  </button>
                  <button type="button" className="p-1 hover:bg-red-100 dark:hover:bg-red-900/30 rounded text-red-500" onClick={() => setIsAddingTag(false)}>
                    <X className="w-3 h-3" />
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>

        <div className="pt-6 flex items-center justify-end gap-3 mt-4 border-t border-gray-200 dark:border-white/10">
          {isEditing && onDelete && (
            <Button 
              type="button" 
              variant="danger" 
              className="mr-auto"
              onClick={() => {
                onDelete(initialData.id);
                onClose();
              }}
            >
              Delete
            </Button>
          )}
          
          <Button type="button" variant="ghost" onClick={onClose}>
            Cancel
          </Button>
          
          <Button type="submit">
            {isEditing ? 'Save Changes' : 'Create Task'}
          </Button>
        </div>
      </form>
    </Modal>
  );
}
